[package]
name = "casco"
version = "0.1.0"
authors = ["Tim <tim@glacyr.com>"]
edition = "2018"
license = "MIT"
description = "CSS-like parser for procedural macros."
repository = "https://github.com/polyhorn/polyhorn/tree/crates/casco"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]

[dependencies]
proc-macro2 = "1.0.19"
itertools = "0.9.0"

[dev-dependencies]
quote = "1.0.7"
